import { TestId } from "./testMeta";
import { Level } from "./testMeta";

export type ProductType = "Practice Book" | "Advanced Book" | "Mock Test" | "Package";

export interface Product {
  id: string;
  slug: string;
  title: string;
  test: TestId;
  skill: string;
  level: Level;
  type: ProductType;
  questions: number;
  pages: number;
  price: number;
  format: string;
  description: string;
  badge?: "BEST" | "NEW" | "PREMIUM";
}

export const products: Product[] = [
  // ---------------- TOEFL ----------------
  {
    id: "toefl-reading-300",
    slug: "toefl-reading-300",
    title: "TOEFL READING 300",
    test: "TOEFL",
    skill: "Reading",
    level: "TARGET",
    type: "Practice Book",
    questions: 300,
    pages: 268,
    price: 29900,
    format: "Digital PDF Workbook",
    description: "TOEFL Reading 핵심 유형을 집중적으로 반복하는 실전 문제집.",
    badge: "BEST",
  },
  {
    id: "toefl-listening-300",
    slug: "toefl-listening-300",
    title: "TOEFL LISTENING 300",
    test: "TOEFL",
    skill: "Listening",
    level: "TARGET",
    type: "Practice Book",
    questions: 300,
    pages: 252,
    price: 29900,
    format: "Digital PDF Workbook + Audio",
    description: "강의, 대화 유형별로 나눈 TOEFL Listening 300문항 집중 훈련.",
  },
  {
    id: "toefl-speaking-100",
    slug: "toefl-speaking-100",
    title: "TOEFL SPEAKING 100",
    test: "TOEFL",
    skill: "Speaking",
    level: "TARGET",
    type: "Practice Book",
    questions: 100,
    pages: 184,
    price: 24900,
    format: "Digital PDF Workbook + Audio",
    description: "Independent·Integrated Task 100문항으로 완성하는 TOEFL Speaking.",
  },
  {
    id: "toefl-writing-80",
    slug: "toefl-writing-80",
    title: "TOEFL WRITING 80",
    test: "TOEFL",
    skill: "Writing",
    level: "TARGET",
    type: "Practice Book",
    questions: 80,
    pages: 176,
    price: 24900,
    format: "Digital PDF Workbook",
    description: "Integrated·Academic Discussion Task를 위한 템플릿 기반 훈련.",
  },
  {
    id: "toefl-vocabulary-1000",
    slug: "toefl-vocabulary-1000",
    title: "TOEFL VOCABULARY 1000",
    test: "TOEFL",
    skill: "Vocabulary",
    level: "FOUNDATION",
    type: "Practice Book",
    questions: 1000,
    pages: 220,
    price: 19900,
    format: "Digital PDF Workbook",
    description: "학술 지문 빈출 어휘 1000개를 주제별로 정리한 기초 어휘집.",
  },
  {
    id: "toefl-reading-advanced",
    slug: "toefl-reading-advanced",
    title: "TOEFL READING ADVANCED",
    test: "TOEFL",
    skill: "Reading",
    level: "ADVANCED",
    type: "Advanced Book",
    questions: 220,
    pages: 244,
    price: 32900,
    format: "Digital PDF Workbook",
    description: "고득점자를 위한 고난도 지문과 추론형 문제 집중 훈련.",
  },
  {
    id: "toefl-full-mock",
    slug: "toefl-full-mock",
    title: "TOEFL FULL MOCK TEST SERIES",
    test: "TOEFL",
    skill: "Mock Test",
    level: "FINAL",
    type: "Mock Test",
    questions: 5,
    pages: 210,
    price: 34900,
    format: "Digital PDF Workbook + Audio",
    description: "실제 시험과 동일한 구성과 시간으로 치르는 Full-Length Mock 5회분.",
  },
  {
    id: "toefl-complete-package",
    slug: "toefl-complete-package",
    title: "TOEFL COMPLETE PACKAGE",
    test: "TOEFL",
    skill: "Mock Test",
    level: "FINAL",
    type: "Package",
    questions: 1500,
    pages: 980,
    price: 79000,
    format: "Digital PDF Workbook Set",
    description: "Reading·Listening·Speaking·Writing·Vocabulary·Mock까지 TOEFL 전 영역 패키지.",
    badge: "PREMIUM",
  },
  {
    id: "toefl-reading-foundation",
    slug: "toefl-reading-foundation",
    title: "TOEFL READING FOUNDATION",
    test: "TOEFL",
    skill: "Reading",
    level: "FOUNDATION",
    type: "Practice Book",
    questions: 180,
    pages: 168,
    price: 19900,
    format: "Digital PDF Workbook",
    description: "TOEFL Reading을 처음 시작하는 학습자를 위한 기본 유형 적응 훈련.",
  },
  {
    id: "toefl-listening-foundation",
    slug: "toefl-listening-foundation",
    title: "TOEFL LISTENING FOUNDATION",
    test: "TOEFL",
    skill: "Listening",
    level: "FOUNDATION",
    type: "Practice Book",
    questions: 160,
    pages: 152,
    price: 19900,
    format: "Digital PDF Workbook + Audio",
    description: "강의·대화 지문에 익숙해지기 위한 TOEFL Listening 기초 훈련.",
  },
  {
    id: "toefl-listening-advanced",
    slug: "toefl-listening-advanced",
    title: "TOEFL LISTENING ADVANCED",
    test: "TOEFL",
    skill: "Listening",
    level: "ADVANCED",
    type: "Advanced Book",
    questions: 200,
    pages: 232,
    price: 32900,
    format: "Digital PDF Workbook + Audio",
    description: "긴 강의와 복잡한 대화문을 다루는 고난도 Listening 훈련.",
  },
  {
    id: "toefl-speaking-advanced",
    slug: "toefl-speaking-advanced",
    title: "TOEFL SPEAKING ADVANCED",
    test: "TOEFL",
    skill: "Speaking",
    level: "ADVANCED",
    type: "Advanced Book",
    questions: 80,
    pages: 168,
    price: 29900,
    format: "Digital PDF Workbook + Audio",
    description: "고득점 답변 구조와 표현 다양성을 위한 Speaking 심화 훈련.",
  },
  {
    id: "toefl-writing-advanced",
    slug: "toefl-writing-advanced",
    title: "TOEFL WRITING ADVANCED",
    test: "TOEFL",
    skill: "Writing",
    level: "ADVANCED",
    type: "Advanced Book",
    questions: 60,
    pages: 172,
    price: 29900,
    format: "Digital PDF Workbook",
    description: "고득점 에세이를 위한 논증 구조와 어휘 심화 훈련.",
  },

  // ---------------- IELTS ----------------
  {
    id: "ielts-academic-reading",
    slug: "ielts-academic-reading",
    title: "IELTS ACADEMIC READING",
    test: "IELTS",
    skill: "Academic Reading",
    level: "TARGET",
    type: "Practice Book",
    questions: 280,
    pages: 256,
    price: 29900,
    format: "Digital PDF Workbook",
    description: "Academic 모듈 3개 지문 유형을 집중적으로 훈련하는 실전 문제집.",
  },
  {
    id: "ielts-listening",
    slug: "ielts-listening",
    title: "IELTS LISTENING",
    test: "IELTS",
    skill: "Listening",
    level: "TARGET",
    type: "Practice Book",
    questions: 240,
    pages: 232,
    price: 29900,
    format: "Digital PDF Workbook + Audio",
    description: "4개 Section 유형별 문제 배치 훈련으로 완성하는 IELTS Listening.",
  },
  {
    id: "ielts-writing-task1",
    slug: "ielts-writing-task1",
    title: "IELTS WRITING TASK 1",
    test: "IELTS",
    skill: "Writing Task 1",
    level: "TARGET",
    type: "Practice Book",
    questions: 60,
    pages: 148,
    price: 24900,
    format: "Digital PDF Workbook",
    description: "그래프, 도표, 다이어그램 유형별 Task 1 모범답안 구조 훈련.",
  },
  {
    id: "ielts-writing-task2",
    slug: "ielts-writing-task2",
    title: "IELTS WRITING TASK 2",
    test: "IELTS",
    skill: "Writing Task 2",
    level: "TARGET",
    type: "Practice Book",
    questions: 60,
    pages: 168,
    price: 29900,
    format: "Digital PDF Workbook",
    description: "에세이 주제별 아이디어 확장과 채점 기준 기반 첨삭 가이드.",
  },
  {
    id: "ielts-speaking",
    slug: "ielts-speaking",
    title: "IELTS SPEAKING",
    test: "IELTS",
    skill: "Speaking",
    level: "TARGET",
    type: "Practice Book",
    questions: 150,
    pages: 176,
    price: 24900,
    format: "Digital PDF Workbook + Audio",
    description: "Part 1·2·3 유형별 모범답안과 표현 확장 훈련.",
  },
  {
    id: "ielts-writing-advanced",
    slug: "ielts-writing-advanced",
    title: "IELTS WRITING ADVANCED",
    test: "IELTS",
    skill: "Writing Task 2",
    level: "ADVANCED",
    type: "Advanced Book",
    questions: 45,
    pages: 152,
    price: 32900,
    format: "Digital PDF Workbook",
    description: "Band 7+ 목표를 위한 고급 어휘·논증 구조 심화 훈련.",
  },
  {
    id: "ielts-academic-mock",
    slug: "ielts-academic-mock",
    title: "IELTS ACADEMIC FULL MOCK",
    test: "IELTS",
    skill: "Mock Test",
    level: "FINAL",
    type: "Mock Test",
    questions: 4,
    pages: 196,
    price: 34900,
    format: "Digital PDF Workbook + Audio",
    description: "Academic 모듈 전 영역을 포함한 Full-Length Mock 4회분.",
  },
  {
    id: "ielts-complete-package",
    slug: "ielts-complete-package",
    title: "IELTS COMPLETE PACKAGE",
    test: "IELTS",
    skill: "Mock Test",
    level: "FINAL",
    type: "Package",
    questions: 1300,
    pages: 920,
    price: 79000,
    format: "Digital PDF Workbook Set",
    description: "Reading·Listening·Writing·Speaking·Mock을 아우르는 IELTS 전 영역 패키지.",
    badge: "PREMIUM",
  },
  {
    id: "ielts-reading-foundation",
    slug: "ielts-reading-foundation",
    title: "IELTS READING FOUNDATION",
    test: "IELTS",
    skill: "Academic Reading",
    level: "FOUNDATION",
    type: "Practice Book",
    questions: 180,
    pages: 172,
    price: 19900,
    format: "Digital PDF Workbook",
    description: "Academic Reading 지문 구조에 익숙해지기 위한 기초 훈련.",
  },
  {
    id: "ielts-listening-foundation",
    slug: "ielts-listening-foundation",
    title: "IELTS LISTENING FOUNDATION",
    test: "IELTS",
    skill: "Listening",
    level: "FOUNDATION",
    type: "Practice Book",
    questions: 160,
    pages: 156,
    price: 19900,
    format: "Digital PDF Workbook + Audio",
    description: "4개 Section의 기본 문제 유형에 익숙해지는 IELTS Listening 기초 훈련.",
  },
  {
    id: "ielts-listening-advanced",
    slug: "ielts-listening-advanced",
    title: "IELTS LISTENING ADVANCED",
    test: "IELTS",
    skill: "Listening",
    level: "ADVANCED",
    type: "Advanced Book",
    questions: 200,
    pages: 224,
    price: 32900,
    format: "Digital PDF Workbook + Audio",
    description: "Section 3·4의 고난도 강의형 지문 집중 훈련.",
  },
  {
    id: "ielts-speaking-advanced",
    slug: "ielts-speaking-advanced",
    title: "IELTS SPEAKING ADVANCED",
    test: "IELTS",
    skill: "Speaking",
    level: "ADVANCED",
    type: "Advanced Book",
    questions: 120,
    pages: 184,
    price: 29900,
    format: "Digital PDF Workbook + Audio",
    description: "Band 7+를 위한 유창성과 어휘 다양성 심화 훈련.",
  },

  // ---------------- PTE ----------------
  {
    id: "pte-speaking-intensive",
    slug: "pte-speaking-intensive",
    title: "PTE SPEAKING INTENSIVE",
    test: "PTE",
    skill: "Speaking",
    level: "TARGET",
    type: "Practice Book",
    questions: 200,
    pages: 188,
    price: 24900,
    format: "Digital PDF Workbook + Audio",
    description: "Read Aloud부터 Retell Lecture까지 AI 채점 대응 전략 훈련.",
  },
  {
    id: "pte-writing",
    slug: "pte-writing",
    title: "PTE WRITING",
    test: "PTE",
    skill: "Writing",
    level: "TARGET",
    type: "Practice Book",
    questions: 120,
    pages: 156,
    price: 24900,
    format: "Digital PDF Workbook",
    description: "Summarize Written Text, Essay 유형 템플릿과 채점 기준 훈련.",
  },
  {
    id: "pte-reading",
    slug: "pte-reading",
    title: "PTE READING",
    test: "PTE",
    skill: "Reading",
    level: "TARGET",
    type: "Practice Book",
    questions: 260,
    pages: 224,
    price: 29900,
    format: "Digital PDF Workbook",
    description: "Reorder Paragraph, Fill in the Blanks 등 PTE 고유 유형 집중 훈련.",
  },
  {
    id: "pte-listening",
    slug: "pte-listening",
    title: "PTE LISTENING",
    test: "PTE",
    skill: "Listening",
    level: "TARGET",
    type: "Practice Book",
    questions: 240,
    pages: 212,
    price: 29900,
    format: "Digital PDF Workbook + Audio",
    description: "Summarize Spoken Text부터 Highlight Incorrect Words까지 전 유형 훈련.",
  },
  {
    id: "pte-integrated-skills",
    slug: "pte-integrated-skills",
    title: "PTE INTEGRATED SKILLS",
    test: "PTE",
    skill: "Integrated Skills",
    level: "ADVANCED",
    type: "Advanced Book",
    questions: 180,
    pages: 200,
    price: 32900,
    format: "Digital PDF Workbook + Audio",
    description: "복수 영역이 결합된 PTE 고유 문항 유형에 대한 고난도 집중 훈련.",
  },
  {
    id: "pte-full-mock",
    slug: "pte-full-mock",
    title: "PTE FULL MOCK TEST",
    test: "PTE",
    skill: "Mock Test",
    level: "FINAL",
    type: "Mock Test",
    questions: 4,
    pages: 184,
    price: 34900,
    format: "Digital PDF Workbook + Audio",
    description: "실제 시험 순서와 시간 배분 그대로 구성한 Full Mock 4회분.",
  },
  {
    id: "pte-complete-package",
    slug: "pte-complete-package",
    title: "PTE COMPLETE PACKAGE",
    test: "PTE",
    skill: "Mock Test",
    level: "FINAL",
    type: "Package",
    questions: 1100,
    pages: 860,
    price: 79000,
    format: "Digital PDF Workbook Set",
    description: "Speaking·Writing·Reading·Listening·Mock을 아우르는 PTE 전 영역 패키지.",
    badge: "PREMIUM",
  },
  {
    id: "pte-speaking-foundation",
    slug: "pte-speaking-foundation",
    title: "PTE SPEAKING FOUNDATION",
    test: "PTE",
    skill: "Speaking",
    level: "FOUNDATION",
    type: "Practice Book",
    questions: 140,
    pages: 148,
    price: 19900,
    format: "Digital PDF Workbook + Audio",
    description: "Read Aloud, Repeat Sentence 등 기본 문항 유형 적응 훈련.",
  },
  {
    id: "pte-writing-advanced",
    slug: "pte-writing-advanced",
    title: "PTE WRITING ADVANCED",
    test: "PTE",
    skill: "Writing",
    level: "ADVANCED",
    type: "Advanced Book",
    questions: 90,
    pages: 176,
    price: 29900,
    format: "Digital PDF Workbook",
    description: "고득점 Essay·Summarize Written Text 심화 훈련.",
  },
  {
    id: "pte-reading-advanced",
    slug: "pte-reading-advanced",
    title: "PTE READING ADVANCED",
    test: "PTE",
    skill: "Reading",
    level: "ADVANCED",
    type: "Advanced Book",
    questions: 200,
    pages: 236,
    price: 32900,
    format: "Digital PDF Workbook",
    description: "Reorder Paragraph 등 고난도 유형 집중 훈련.",
  },
  {
    id: "pte-listening-advanced",
    slug: "pte-listening-advanced",
    title: "PTE LISTENING ADVANCED",
    test: "PTE",
    skill: "Listening",
    level: "ADVANCED",
    type: "Advanced Book",
    questions: 200,
    pages: 220,
    price: 32900,
    format: "Digital PDF Workbook + Audio",
    description: "Summarize Spoken Text 등 고난도 Listening 유형 심화 훈련.",
  },

  // ---------------- DET ----------------
  {
    id: "det-full-practice-tests",
    slug: "det-full-practice-tests",
    title: "DET FULL PRACTICE TESTS",
    test: "DET",
    skill: "Mock Test",
    level: "FINAL",
    type: "Mock Test",
    questions: 4,
    pages: 176,
    price: 29900,
    format: "Digital PDF Workbook + Audio",
    description: "적응형 채점 방식까지 반영한 Duolingo English Test 실전 모의고사.",
    badge: "BEST",
  },
  {
    id: "det-reading",
    slug: "det-reading",
    title: "DET READING",
    test: "DET",
    skill: "Reading",
    level: "TARGET",
    type: "Practice Book",
    questions: 220,
    pages: 188,
    price: 24900,
    format: "Digital PDF Workbook",
    description: "Fill in the Blanks 등 DET 고유 Reading 유형 집중 훈련.",
  },
  {
    id: "det-interactive-reading",
    slug: "det-interactive-reading",
    title: "DET INTERACTIVE READING",
    test: "DET",
    skill: "Interactive Reading",
    level: "TARGET",
    type: "Practice Book",
    questions: 140,
    pages: 144,
    price: 24900,
    format: "Digital PDF Workbook",
    description: "지문 기반 Interactive 문항의 구조를 익히는 전용 훈련서.",
  },
  {
    id: "det-interactive-listening",
    slug: "det-interactive-listening",
    title: "DET INTERACTIVE LISTENING",
    test: "DET",
    skill: "Interactive Listening",
    level: "TARGET",
    type: "Practice Book",
    questions: 140,
    pages: 148,
    price: 24900,
    format: "Digital PDF Workbook + Audio",
    description: "실시간 받아쓰기형 문항 등 DET Listening 고유 유형 훈련.",
  },
  {
    id: "det-speaking-writing",
    slug: "det-speaking-writing",
    title: "DET SPEAKING & WRITING",
    test: "DET",
    skill: "Speaking",
    level: "TARGET",
    type: "Practice Book",
    questions: 160,
    pages: 172,
    price: 24900,
    format: "Digital PDF Workbook + Audio",
    description: "사진 설명, 의견 말하기 등 Speaking·Writing 통합 유형 훈련.",
  },
  {
    id: "det-adaptive-practice",
    slug: "det-adaptive-practice",
    title: "DET ADAPTIVE PRACTICE",
    test: "DET",
    skill: "Adaptive Practice",
    level: "ADVANCED",
    type: "Advanced Book",
    questions: 200,
    pages: 168,
    price: 32900,
    format: "Digital PDF Workbook",
    description: "난이도가 상승하는 적응형 출제 방식에 맞춘 고난도 훈련.",
  },
  {
    id: "det-complete-package",
    slug: "det-complete-package",
    title: "DET COMPLETE PACKAGE",
    test: "DET",
    skill: "Mock Test",
    level: "FINAL",
    type: "Package",
    questions: 900,
    pages: 720,
    price: 69000,
    format: "Digital PDF Workbook Set",
    description: "Reading·Listening·Speaking·Writing·Mock까지 DET 전 영역 패키지.",
    badge: "PREMIUM",
  },
  {
    id: "det-reading-foundation",
    slug: "det-reading-foundation",
    title: "DET READING FOUNDATION",
    test: "DET",
    skill: "Reading",
    level: "FOUNDATION",
    type: "Practice Book",
    questions: 160,
    pages: 144,
    price: 19900,
    format: "Digital PDF Workbook",
    description: "DET 고유 Reading 유형에 처음 익숙해지는 기초 훈련.",
  },
  {
    id: "det-writing",
    slug: "det-writing",
    title: "DET WRITING",
    test: "DET",
    skill: "Writing",
    level: "TARGET",
    type: "Practice Book",
    questions: 130,
    pages: 140,
    price: 24900,
    format: "Digital PDF Workbook",
    description: "사진 묘사, 의견 작문 등 DET Writing 문항 유형 집중 훈련.",
  },
  {
    id: "det-speaking-advanced",
    slug: "det-speaking-advanced",
    title: "DET SPEAKING ADVANCED",
    test: "DET",
    skill: "Speaking",
    level: "ADVANCED",
    type: "Advanced Book",
    questions: 120,
    pages: 156,
    price: 29900,
    format: "Digital PDF Workbook + Audio",
    description: "고득점 유창성과 논리 전개를 위한 Speaking 심화 훈련.",
  },

  // ---------------- JUNIOR ----------------
  {
    id: "toefl-junior-reading",
    slug: "toefl-junior-reading",
    title: "TOEFL JUNIOR READING",
    test: "JUNIOR",
    skill: "Academic Reading",
    level: "FOUNDATION",
    type: "Practice Book",
    questions: 200,
    pages: 176,
    price: 22900,
    format: "Digital PDF Workbook",
    description: "국제학교·유학 준비생을 위한 TOEFL Junior 기초 독해 훈련.",
  },
  {
    id: "toefl-primary-english",
    slug: "toefl-primary-english",
    title: "TOEFL PRIMARY ENGLISH",
    test: "JUNIOR",
    skill: "Academic Vocabulary",
    level: "FOUNDATION",
    type: "Practice Book",
    questions: 180,
    pages: 160,
    price: 22900,
    format: "Digital PDF Workbook",
    description: "저학년 학습자를 위한 TOEFL Primary 기초 문형·어휘 훈련.",
  },
  {
    id: "international-school-english",
    slug: "international-school-english",
    title: "INTERNATIONAL SCHOOL ENGLISH",
    test: "JUNIOR",
    skill: "Academic Reading",
    level: "FOUNDATION",
    type: "Practice Book",
    questions: 210,
    pages: 184,
    price: 24900,
    format: "Digital PDF Workbook",
    description: "국제학교 커리큘럼에 맞춘 학술 영어 기초 다지기.",
  },
  {
    id: "toefl-junior-listening",
    slug: "toefl-junior-listening",
    title: "TOEFL JUNIOR LISTENING",
    test: "JUNIOR",
    skill: "Academic Reading",
    level: "FOUNDATION",
    type: "Practice Book",
    questions: 150,
    pages: 144,
    price: 22900,
    format: "Digital PDF Workbook + Audio",
    description: "국제학교·유학 준비생을 위한 TOEFL Junior 기초 듣기 훈련.",
  },
  {
    id: "academic-vocabulary-foundation",
    slug: "academic-vocabulary-foundation",
    title: "ACADEMIC VOCABULARY FOUNDATION",
    test: "JUNIOR",
    skill: "Academic Vocabulary",
    level: "FOUNDATION",
    type: "Practice Book",
    questions: 500,
    pages: 132,
    price: 19900,
    format: "Digital PDF Workbook",
    description: "국제학교 저학년 학습자를 위한 학술 어휘 기초 500단어.",
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getRelatedProducts(product: Product, count = 3): Product[] {
  return products
    .filter((p) => p.id !== product.id && p.test === product.test)
    .slice(0, count);
}

export const bestSellerIds = [
  "toefl-reading-300",
  "toefl-listening-300",
  "toefl-speaking-100",
  "ielts-academic-reading",
  "ielts-writing-task2",
  "pte-speaking-intensive",
  "det-full-practice-tests",
  "toefl-complete-package",
];

export const bestSellers = bestSellerIds
  .map((id) => products.find((p) => p.id === id))
  .filter((p): p is Product => Boolean(p));
